# -*- coding: utf-8 -*-
"""csv_tranformar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1InYhJQGm99CpZtr8JY29qGSTbh49u-OZ
"""

!pip install dbfread

from dbfread import DBF
import pandas as pd

# Carregar o arquivo DBF
dbf_table_acarau = DBF('/content/acarau.dbf', encoding='latin1')

# Carregar o arquivo DBF
dbf_table_bela_cruz = DBF('/content/bela_cruz.dbf', encoding='latin1')

# Carregar o arquivo DBF
dbf_table_cruz = DBF('/content/cruz.dbf', encoding='latin1')

# Carregar o arquivo DBF
dbf_table_itarema = DBF('/content/itarema.dbf', encoding='latin1')

# Carregar o arquivo DBF
dbf_table_jijoca = DBF('/content/jijoca.dbf', encoding='latin1')

# Carregar o arquivo DBF
dbf_table_marco = DBF('/content/marco.dbf', encoding='latin1')

# Carregar o arquivo DBF
dbf_table_morrinhos = DBF('/content/morrinhos.dbf', encoding='latin1')

# Converter para DataFrame

df_acarau = pd.DataFrame(iter(dbf_table_acarau))
df_bela_cruz = pd.DataFrame(iter(dbf_table_bela_cruz))
df_cruz = pd.DataFrame(iter(dbf_table_cruz))
df_itarema = pd.DataFrame(iter(dbf_table_itarema))
df_jijoca = pd.DataFrame(iter(dbf_table_jijoca))
df_marco = pd.DataFrame(iter(dbf_table_marco))
df_morrinhos = pd.DataFrame(iter(dbf_table_morrinhos))

# Lista de DataFrames para concatenar
dfs = [df_acarau, df_bela_cruz, df_cruz, df_itarema, df_jijoca, df_marco, df_morrinhos]

# Concatena os DataFrames verticalmente (adiciona as linhas)
df_final = pd.concat(dfs, ignore_index=True)

df_final.to_csv("dados_combinados.csv", index=False, encoding='utf-8')